const DUMMY_PROFILES = [
  {
    id: "e1",
    title: "Contact Email not Linked",
    updated: "Updated 1 day ago",
    customer: " Tom Cruise",
    join: "on 24.05.2019",
    date: "May 26, 2019",
    time: "6:30 PM",
    image: "assets/e1.png",
    priority: "HIGH",
  },
  {
    id: "e2",
    title: "Adding Images to Featured Posts",
    updated: "Updated 1 day ago",
    customer: " Matt Damon",
    join: "on 24.05.2019",
    date: "May 26, 2019",
    time: "6:30 PM",
    image: "assets/e2.png",
    priority: "LOW",
  },
  {
    id: "e3",
    title: "When will I be charged this month?",
    updated: "Updated 1 day ago",
    customer: " Robert Downey",
    join: "on 24.05.2019",
    date: "May 26, 2019",
    time: "6:30 PM",
    image: "assets/e3.png",
    priority: "HIGH",
  },
  {
    id: "e4",
    title: "Payment not going through",
    updated: "Updated 2 day ago",
    customer: " Christian Bale",
    join: "on 24.05.2019",
    date: "May 25, 2019",
    time: "5:00 PM",
    image: "assets/e4.png",
    priority: "NORMAL",
  },
  {
    id: "e5",
    title: "Unable to add replies",
    updated: "Updated 2 day ago",
    customer: " Henry Cavil",
    join: "on 24.05.2019",
    date: "May 25, 2019",
    time: "4:00 PM",
    image: "assets/e5.png",
    priority: "HIGH",
  },
  {
    id: "e6",
    title: "Downtime since last week",
    updated: "Updated 3 day ago",
    customer: " Chris Evans",
    join: "on 23.05.2019",
    date: "May 25, 2019",
    time: "2:00 PM",
    image: "assets/e6.png",
    priority: "NORMAL",
  },
  {
    id: "e7",
    title: "Referral Bonus",
    updated: "Updated 4 day ago",
    customer: " Sam Smith",
    join: "on 22.05.2019",
    date: "May 25, 2019",
    time: "11:30 AM",
    image: "assets/e7.png",
    priority: "LOW",
  },
  {
    id: "e8",
    title: "How do I change my password?",
    updated: "Updated 6 day ago",
    customer: " Steve Rogers",
    join: "on 21.05.2019",
    date: "May 24, 2019",
    time: "1:00 PM",
    image: "assets/e8.png",
    priority: "NORMAL",
  },
];

export default DUMMY_PROFILES;
